title:            "@yellowdi"
url:              http://yellowdi.github.io/
permalink:        pretty
google_analytics: UA-67750264-4
timezone:         Asia/Shanghai
sass:
  sass_dir: assets
  style: :compressed
