# Meta

title:         "@yellowdi"
description:   "blog"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://yellowdi.github.io
fontawesome:   https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
exclude:       ['fontawesome', 'node_modules', 'templates', '.babelrc', 'elenore-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']
